<a href="https://colab.research.google.com/github/Aerospace-prog/Python-For-AI-Ml/blob/main/Python_For_Ai_Ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Strings**

There are three primary ways to declare strings in Python:

1.  **Single Quotes (`'`)**: Useful for simple, single-line strings.
2.  **Double Quotes (`"`)**: Also used for simple, single-line strings. Often preferred when the string contains single quotes.
3.  **Triple Quotes (`"""` or `'''`)**: Used for multi-line strings, which can span across multiple lines in your code. These are also commonly used for docstrings.

In [ ]:
# Kinds of string declarations

str1 = 'hello'
str2 = "hello"
str3 = """hello
          kaise ho aap
        """

 # Note : Strings are immutable in nature


print(len(str2)) # ==> 5



5


**Indexing in strings**

Indexing in strings allows you to access individual characters within a string using their position (index).

*   **Positive Indexing**: Starts from 0 for the first character and increases by 1 for each subsequent character.
*   **Negative Indexing**: Starts from -1 for the last character and decreases by 1 for each preceding character.

You can access a character using square brackets `[]` with the index inside.

In [ ]:
# Let's assume we have a string for demonstration
str2 = "HelloWorld"

# str2[0:4] → Extracts characters from index 0 to 3 (end index 4 is excluded).
# This means it will take the substring "Hell".
print(str2[0:4])   # Output: Hell

# str2[:] → Returns the entire string because no start or end index is given.
# This is the same as making a copy of the string.
print(str2[:])     # Output: HelloWorld

# str2[:4] → Omits the start index (defaults to 0) and goes till index 3.
# Equivalent to str2[0:4].
print(str2[:4])    # Output: Hell

# str2[0:] → Omits the end index (defaults to the end of the string).
# Extracts from index 0 to the end.
print(str2[0:])    # Output: HelloWorld

Hell
HelloWorld
Hell
HelloWorld


**Slicing with 3 parameters - [startindex : endindex : step]**

In [ ]:
numStr = "0123456789"

# Start at index 2 and take every 2nd character → indices 2,4,6,8
print(numStr[2::2])   # Output: 2468

# Start at index 1 and take every 2nd character → indices 1,3,5,7,9
print(numStr[1::2])   # Output: 13579

characterAtIndex1 = numStr[1]
print(characterAtIndex1)

#Type Checking for string
print(type(characterAtIndex1))



exampleString = "Aerospace"

# Negative slicing counts from the end:
# Index positions:  A   e   r   o   s   p   a   c   e
# Positive index:   0   1   2   3   4   5   6   7   8
# Negative index:  -9  -8  -7  -6  -5  -4  -3  -2  -1

# exampleString[-6:-1] → take characters from -6 (index of 'o') up to -1 (excluded, index of 'e')
print(exampleString[-6:-1])   # Output: ospac

2468
13579
1
<class 'str'>
ospac


**String Functions**

In [ ]:
randomStr = "polarisSchoolofTech"

# Get the total number of characters in the string
print(len(randomStr))   # Output: 18

# Capitalize the first character, rest in lowercase
print(randomStr.capitalize())   # Output: Polarisschooloftech

# Convert entire string to uppercase
print(randomStr.upper())   # Output: POLARISSCHOOLOFTECH

# Convert entire string to lowercase
print(randomStr.lower())   # Output: polarisschooloftech

# Check if string starts with "polaris"
print(randomStr.startswith("polaris"))   # Output: True

# Check if string ends with "techonologia"
print(randomStr.endswith("techonologia"))   # Output: False

# Convert string into Title Case (first letter of each word capitalized)
print(randomStr.title())   # Output: Polarisschooloftech

# Make only the first 7 characters uppercase
print(randomStr[:7].upper())   # Output: POLARIS

# Find index of first occurrence of substring "School" (-1 if not found)
print(randomStr.find("School"))   # Output: 7

# Replace "SchoolofTech" with "SchoolOfHack"
print(randomStr.replace("SchoolofTech", "SchoolOfHack"))   # Output: polarisSchoolOfHack

# Count occurrences of 'o'
print(randomStr.count("o"))   # Output: 3


# PROBLEM : 1 - FIND ALL WHITESPACES INDEX IN WHOLE STRING :)

text = "Python is a fun programming language"

# find first whitespace
pos = text.find(' ')

while pos != -1:   # keep looping until no space is found
    print("Whitespace found at index:", pos)

    # find next whitespace starting after current position
    pos = text.find(' ', pos + 1)

19
Polarisschooloftech
POLARISSCHOOLOFTECH
polarisschooloftech
True
False
Polarisschooloftech
POLARIS
7
polarisSchoolOfHack
4
Whitespace found at index: 6
Whitespace found at index: 9
Whitespace found at index: 11
Whitespace found at index: 15
Whitespace found at index: 27


# **Functions in python**

Functions in Python are blocks of reusable code that perform a specific task. They help organize code, make it more readable, and reduce redundancy.

**Key Concepts:**

*   **Defining a Function:** Functions are defined using the `def` keyword, followed by the function name, parentheses `()`, and a colon `:`. The code block for the function is indented.
*   **Function Name:** Should be descriptive and follow Python naming conventions (lowercase with underscores).
*   **Parameters:** These are values passed into the function when it is called. They are specified within the parentheses in the function definition.
*   **Arguments:** These are the actual values passed to the function when it is called.
*   **Return Statement:** The `return` keyword is used to send a value back from the function to the part of the code that called it. If no `return` statement is used, the function returns `None` by default.
*   **Calling a Function:** To execute the code within a function, you "call" it by using the function name followed by parentheses `()`, including any necessary arguments.

**Benefits of using Functions:**

*   **Reusability:** Write code once and use it multiple times.
*   **Modularity:** Break down complex problems into smaller, manageable parts.
*   **Readability:** Makes code easier to understand and maintain.
*   **Abstraction:** Hide the complex details of a task behind a simple function call.

In [ ]:
num1 = int(input("Enter Number 1 "))

num2 = int(input("Enter Number 2 "))

sum  = num1 + num2

print(f"The sum of these numbers is : {sum}")

Enter Number 1 12
Enter Number 2 23
The sum of these numbers is : 35


In [ ]:
def calulateNums() : #Function declaration
  num1 = int(input("Enter Number 1 "))
  num2 = int(input("Enter Number 2 "))
  sum  = num1 + num2                              #Function definition
  print(f"The sum of these numbers is : {sum}")


calulateNums() #Function call

Enter Number 1 12
Enter Number 2 12
The sum of these numbers is : 24
Enter number to get cube1
The cube of 1 is 1


In [ ]:
def cube() :
  num1 = int(input("Enter number to get cube "))
  cube = num1 * num1 * num1
  print(f"The cube of {num1} is {cube}")

cube()

Enter number to get cube 2
The cube of 2 is 8


**Function With Arguments**

There are two types of functions in python = 1. Built in. 2. User defined

In [ ]:
def greet(name) :
  print(f"Good Afternoon{name}")

greet("Aerospace")


def greet1(name , title = "CHIP"):
  print(f"Hello Coder {name} {title}")

greet1("Aerosapce", 'Prog')

Good AfternoonAerospace
Hello Coder Aerosapce Prog


In [ ]:
def func1(val):
  return val

func1(12)

12

Recursion Example for function


In [ ]:
def fact (n) :
  if(n == 1 or n == 0):
    return 1

  return n * fact(n-1)

print(fact(5))

120


# **Collections**

Collections in Python are containers that are used to store collections of data. They are a fundamental part of Python and are used extensively in programming. Python offers several built-in collection types, each with its own characteristics and use cases.

**Key Built-in Collection Types:**

1.  **Lists (`list`)**:
    *   Ordered, mutable (changeable) sequence of elements.
    *   Elements are enclosed in square brackets `[]`.
    *   Can contain elements of different data types.
    *   Supports indexing and slicing.
    *   Examples: `[1, 2, 3]`, `['apple', 'banana', 'cherry']`

2.  **Tuples (`tuple`)**:
    *   Ordered, immutable (unchangeable) sequence of elements.
    *   Elements are enclosed in parentheses `()`.
    *   Can contain elements of different data types.
    *   Supports indexing and slicing.
    *   Often used for heterogeneous data (different types) and when the sequence of elements is fixed.
    *   Examples: `(1, 2, 3)`, `('apple', 'banana')`

3.  **Sets (`set`)**:
    *   Unordered collection of unique elements.
    *   Elements are enclosed in curly braces `{}` (except for an empty set, which is created using `set()`).
    *   Does not support indexing or slicing.
    *   Useful for membership testing, removing duplicates, and performing mathematical set operations (union, intersection, difference).
    *   Examples: `{1, 2, 3}`, `{'apple', 'banana'}`

4.  **Dictionaries (`dict`)**:
    *   Unordered collection of key-value pairs.
    *   Key-value pairs are enclosed in curly braces `{}`.
    *   Keys must be unique and immutable (like strings, numbers, or tuples).
    *   Values can be of any data type.
    *   Used to store data in a key-value format for efficient lookup.
    *   Examples: `{'name': 'John', 'age': 30}`, `{'a': 1, 'b': 2}`

Understanding these collection types and their differences is crucial for writing efficient and effective Python code.

**List**

In [ ]:
#List - Mutable and indexing maintained

list = [1,2,"hello",3,4,5,True , False , None , "hi" , 1.2]

#Get Element by indexing
print(list[1])
#Print Whole list
print(list)
#List Iterator
for i in list:
  print(i)

# Slicing in list
print(list[0:4])
print(list[::2])
print(list[::4])

#Functions in list
list1 = [1,232,453,6,4,32,97]

list1.sort()
print(list1)

list1.reverse()
print(list1)

list1.append(20)
print(list1)

list1.insert(3,47)
print(list1)

list1.index(32)

list1.pop(3)
print(list1)

list1.remove(453)
print(list1)

"""
Features of List :
ordered collection of elements
heterogenours data
mutable
indexing/slicing
allow duplicates
nested list allowed
itetrable
non - hashable

"""

2
[1, 2, 'hello', 3, 4, 5, True, False, None, 'hi', 1.2]
1
2
hello
3
4
5
True
False
None
hi
1.2
[1, 2, 'hello', 3]
[1, 'hello', 4, True, None, 1.2]
[1, 4, None]
[1, 4, 6, 32, 97, 232, 453]
[453, 232, 97, 32, 6, 4, 1]
[453, 232, 97, 32, 6, 4, 1, 20]
[453, 232, 97, 47, 32, 6, 4, 1, 20]
[453, 232, 97, 32, 6, 4, 1, 20]
[232, 97, 32, 6, 4, 1, 20]


In [ ]:
listexample = [1,2,3,4,5,6,70]
def add(listexample):
  sum = 0
  for i in listexample:
    sum = sum + i
  return sum

print(add(listexample))

91


**Tuples**

In [ ]:
#Tuple declaration

t1 = (1,2,3,3,3,"hello",True)
t2 = ()
t3 = (1,)

t1.count(3)

print(t1)

#Iterator in tuple
for i in t1:
  print(i)

print(t1[1])

#Slicing
print(t1[0:4])
print(t1[::2])
print(t1[::3])

(1, 2, 3, 3, 3, 'hello', True)
1
2
3
3
3
hello
True
2
(1, 2, 3, 3)
(1, 3, 3, True)
(1, 3, True)


**Functions In Tuple**

In [ ]:
t1.count(3)

t1.index("hello")

'''
  Features of Tuple :
  ordered collection of elements
  heterogenours data
  immutable
  indexing/slicing
  allow duplicates
  nested tuple allowed
  itetrable
  hashable
'''

5

**Dictionary**

In [ ]:
dict1 = {
    "key" : "value",
    1 : "hello",
    2 : "yellow",
    3 : "aerospace",
    "hi" : "bye",
    "bool" : True,
    "list" : [1,2,3,4,5],
    "tuple" : (1,2)
}
#The Key should be hashable --> unique/immutable

print(dict1)

# TO delete element there is only pop() method
dict1.pop("tuple")
print(dict1)


{'key': 'value', 1: 'hello', 2: 'yellow', 3: 'aerospace', 'hi': 'bye', 'bool': True, 'list': [1, 2, 3, 4, 5], 'tuple': (1, 2)}
{'key': 'value', 1: 'hello', 2: 'yellow', 3: 'aerospace', 'hi': 'bye', 'bool': True, 'list': [1, 2, 3, 4, 5]}


**Set - A set is an unordered collection of unique elements.**

In [ ]:
# Declaration:
s = set()
s.add(5)
s.add(24)
s.add("hello")
s.add(True)
s.add(1) # Duplicate of True → ignored
s.add(0) # Duplicate of False → ignored
print(s)
s1 = {123, 344, "hello", True, 1, 0, False}
print(s1)

{0, True, 5, 'hello', 24}
{0, True, 'hello', 344, 123}


In [ ]:
# Set Functions:
print(len(s1)) # Length of set
s1.remove(123) # Remove specific element
s1.pop() # Removes random element
s.clear() # Empty set
s1.update([67, 3, 4], {8, 11}) # Add multiple elements
print(s1)
print(s1.union({123, 345, 33})) # Union
print(s1 | {123, 345, 33}) # Equivalent union operator
print(s1.intersection({67, 3, 48})) # Intersection
print(s1 & {67, 3, 48}) # Equivalent intersection operator

# Features of a Set
# ● Unordered → no indexing.
# ● Mutable → elements can be added/removed.
# ● No duplicates → {1, True} collapses to {1}.
# ● Heterogeneous elements allowed (numbers, strings, tuples).
# ● Supports Union (|) and Intersection (&).

# File IO

**File I/O in Python**

File Input/Output (I/O) in Python allows you to interact with files on your computer. This means you can read data from files and write data to files.

Key concepts:

*   **Opening a File:** You need to open a file before you can read from it or write to it. The `open()` function is used for this. You specify the file path and the mode (e.g., 'r' for read, 'w' for write, 'a' for append).
*   **File Modes:** Different modes determine how the file is opened:
    *   `'r'` (read): Opens a file for reading. The file pointer is at the beginning.
    *   `'w'` (write): Opens a file for writing. Creates a new file if it doesn't exist or truncates the file if it exists.
    *   `'a'` (append): Opens a file for appending. Creates a new file if it doesn't exist. Data is written at the end of the file.
    *   `'x'` (exclusive creation): Creates a new file, but raises an error if the file already exists.
    *   `'t'` (text mode): The default mode. Data is treated as text.
    *   `'b'` (binary mode): Data is treated as binary.
*   **Reading from a File:** After opening in read mode, you can use methods like `read()`, `readline()`, or `readlines()` to get data from the file.
*   **Writing to a File:** After opening in write or append mode, you can use the `write()` method to put data into the file.
*   **Closing a File:** It's crucial to close a file after you're done with it using the `close()` method. This releases the file resources. Using `with open(...) as file:` is the recommended way as it automatically closes the file.

In [ ]:
# There is a function which solves a purpose.

# The place of execution of any program would be your RAM

# The RAM is a volatile form of memory in which all your contents are lost , once the program terminates

# To store any form of a permanently your need files

# HDD & SSD is a form of non-volatile memory which can save files permanently



In [ ]:
# Reading from Text files and writing into text files

from google.colab import files
uploaded = files.upload() # This variable is form of collection

for filename in uploaded:
  # Opens the file
  f = open(filename) #open() function - ("filename" , "operation")
  # Read the file
  data = f.read()
  #prints the data
  print(data)
  #close the file
  f.close()


Saving test.txt to test (3).txt
Hello this is text file
This is second line 
This is third line


In [ ]:
#read() function variants

#readline()
#readlines()
# with - Helps you avoid explicit declaration of close()


# for filename in uploaded:
#   with open(filename, "r") as f:
#     line1 = f.readline()
#     print(line1,type(line1))
#     line2 = f.readline()
#     print(line2,type(line2))
#     line3 = f.readline()
#     print(line3,type(line3))

# for filename in uploaded:
#   with open(filename, "r") as f:
#     lines = f.readlines()
#     print(lines,type(lines))

#PRACTICE :- read from a file name animals.txt and check whether the file contains the word "hen" in it
# from google.colab import files
# uploaded = files.upload()

# for filename in uploaded:
#   with open(filename, "r") as f:
#     lines = f.readlines()
#     for line in lines:
#       if "hen" in line:
#         print(True)
#         break
#       else :
#         print(False)
#         break


# WRITE OPERATION

# f = open("test.txt", "w")
# newStr = "Hello Duniya!"
# f.write(newStr)
# f.close()

# write() is a method used with file objects in Python to write a string to a file.
# Write() with a capital 'W' is not a standard method in Python for file handling. It might be a typo or a method from a specific library or custom class.

#HERE THIS WILL NOT WORK


#APPEND OPERATION

# f = open("test.txt" , "a")
# addedStr = "\n This is new line added with append"
# f.write(addedStr)
# f.close()

"""
  Python File Modes - Definitions
===============================

Basic Modes
-----------
r   = Open for reading only (default). File must exist.
w   = Open for writing only. Creates a new file or truncates (empties) the file if it exists.
a   = Open for appending only. Creates file if it does not exist, otherwise writes at the end.

With '+' (Read + Write)
-----------------------
r+  = Open for reading and writing. File must exist. No truncation.
w+  = Open for reading and writing. Truncate file first (empties it if it exists).
a+  = Open for reading and appending. File pointer is at the end, but you can still read.

Binary / Text Modes
-------------------
rb  = Open for reading binary (e.g., images, videos). File must exist.
wb  = Open for writing binary. Truncate file first (create new if not exists).
ab  = Open for appending binary.

rt  = Open for reading text (default mode). Same as "r".
wt  = Open for writing text (truncate file). Same as "w".
at  = Open for appending text. Same as "a".

Combos
------
r+b or rb+ = Read & write binary. File must exist.
w+b or wb+ = Read & write binary, truncate first.
a+b or ab+ = Read & write binary, append if file exists.

Quick Summary Table
-------------------
| Mode | File Must Exist? | Truncate? | Pointer | Read | Write |
|------|------------------|-----------|---------|------|-------|
| r    | Yes              | No        | Start   | Yes  | No    |
| w    | No (creates)     | Yes       | Start   | No   | Yes   |
| a    | No (creates)     | No        | End     | No   | Yes   |
| r+   | Yes              | No        | Start   | Yes  | Yes   |
| w+   | No (creates)     | Yes       | Start   | Yes  | Yes   |
| a+   | No (creates)     | No        | End     | Yes  | Yes   |
| rb   | Yes              | No        | Start   | Yes  | No    |
| wb   | No (creates)     | Yes       | Start   | No   | Yes   |
| ab   | No (creates)     | No        | End     | No   | Yes   |
"""


Saving animals.txt to animals (6).txt
True


In [ ]:
# WAP to write tables from 2 to 20 in differend text files. Store them in a folder.

# for num in range(2, 21):
#     file_path = f"tables/table_{num}.txt"

#     with open(file_path, "w") as f:
#         f.write(f"Multiplication Table of {num}\n")
#         f.write("=" * 30 + "\n")
#         for i in range(1, 11):
#             f.write(f"{num} x {i} = {num * i}\n")

# print("Tables from 2 to 20 have been written inside the 'tables' folder ")


# NumPy

*NumPy*

NumPy (Numerical Python) is a fundamental library for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

**Key Features:**

*   **Powerful N-dimensional array object:** This is the core of NumPy, allowing efficient storage and manipulation of large datasets.
*   **Broadcasting:** A powerful feature that allows NumPy to work with arrays of different shapes when performing arithmetic operations.
*   **Integration:** NumPy is designed to be highly integrated with other scientific computing libraries like SciPy and Matplotlib.
*   **Performance:** NumPy operations are often much faster than equivalent Python list operations due to its underlying implementation in C.

**Why use NumPy?**

*   **Efficiency:** Working with large datasets is significantly faster.
*   **Convenience:** Provides a wide range of mathematical functions and operations that are easy to use.
*   **Foundation:** Many other scientific and data analysis libraries in Python are built on top of NumPy.

In [ ]:
                                                                  # FEATURES
# Numpy works with multi dimentional arrays
# This is an open source library which is built on python and C
# The kinds of operations on arrays numpy supports are :
## Array initialization
## Array Slicing
## Array Reshaping
## Supports zero , one and two (matrix) dimentional arrays
## Array join , Array Split

In [ ]:
#Installing numpy
!pip install numpy

In [ ]:
import numpy as np

#Function to create numpy arrays - numpy.array()
#Two ways to create numpy arrays - 1.Passing a list , 2. Passing a tuple

#1. Passing a tuple
npobj = np.array((1,2,3,4,5,6,7,8,9))
print(npobj)
print(type(npobj)) # N-Dimentional array

#2. Passing a list
npobj = np.array([1,2,3,4,5,6,7,8,9])
print(npobj)
print(type(npobj)) # N-Dimentional array

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


 **Dimensions of a Numpy Array**

 **To check the dimensions of a numpy array we make use of the attribute 'ndim'**

 *The kinds of Arrays that can be created are :*

 Zero Dimensional Array
 One Dimensional Array
 Two Dimensional Array (basically a matrix)

In [ ]:
# 1. Zero Dimensional Array

import numpy as np

zero_dim_arr = np.array(42)

print(zero_dim_arr)
print(type(zero_dim_arr))
print(f"Dimension : {zero_dim_arr.ndim}")

42
<class 'numpy.ndarray'>
Dimension : 0


In [ ]:
# 2. One Dimensional Array

import numpy as np

one_dim_arr = np.array([1, 2, 3, 4, 5])

print(one_dim_arr)
print(type(one_dim_arr))
print(f"Dimension : {one_dim_arr.ndim}")

[1 2 3 4 5]
<class 'numpy.ndarray'>
Dimension : 1


In [ ]:
# 3. Two Dimensional Array

import numpy as np

two_dim_arr = np.array( [ [1,2,3,4],[5,6,7,8] ] ) # This should always be structured
print(two_dim_arr)
print(type(two_dim_arr))
print(f"Dimension : {two_dim_arr.ndim}")

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
Dimension : 2


### Initializing an Array

In [ ]:
# Initializing an array

# To Initialize an empty array in numpy we use numpy.zeros() function where inside params we have (rows,columns)

import numpy as np

initArray = np.zeros( [3,4] )
print(initArray)
print(type(initArray))
print(f"Dimension : {initArray.ndim}")

# Initialize this array with some values using loops
# Make use of np.shape() - Shape is used to get elements/whole list inside matrix

arr1 = np.zeros( [2,2] )
for i in range(arr1.shape[0]):
  for j in range(arr1.shape[1]):
    arr1[i,j] = (i+1) * (j+1)

print(arr1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>
Dimension : 2
[[1. 2.]
 [2. 4.]]


### Data Types in Numpy

In [ ]:
# Kinds of dtypes supported in NumPy:

# Code  | Description
# -----------------------------------
# b     | Boolean
# u     | Unsigned Integer
# m     | Timedelta64
# M     | Datetime64
# U     | Unicode String
# i     | Signed Integer
# f     | Floating Point
# c     | Complex Floating Point
# O     | Object

# To Determine the kind if data the array is holding , we use the 'dtype' attrubute

import numpy as np


int_arr = np.array( [1,2,4] )
print(int_arr)
print(int_arr.dtype) # int64


str_arr = np.array( ["hello" , "world"] )
print(str_arr)
print(str_arr.dtype) # <U5 - U(Unicode String) , 5(The maximum characters inside string model)



[1 2 4]
int64
['hello' 'world']
<U5


In [ ]:
# Type conversion in numpy array
# The function used for type conversion is "astype()"

import numpy as np

typearray = np.array(["1","2","3","4","5"])
print(typearray)
print(typearray.dtype)
type2array = typearray.astype("i")
print(type2array)
print(type2array.dtype)


type3array = np.array([1,2,3,4,5,6])
typestrarray = type3array.astype("S")
print(typestrarray)
print(typestrarray.dtype)

# Using dtype() to convert
type_array = np.array(["abs","asas","wer","asas"] , dtype = "S4")
print(type_array)
print(type_array.dtype)


['1' '2' '3' '4' '5']
<U1
[1 2 3 4 5]
int32
[b'1' b'2' b'3' b'4' b'5' b'6']
|S21
[b'abs' b'asas' b'wer' b'asas']
|S4


In [ ]:
# Type declarations array one by one

booleanarray = np.array([True,False,True,False])
print(booleanarray)
print(booleanarray.dtype)

intarray = np.array([1,2,3,4,5])
print(intarray)
print(intarray.dtype)

strarray = np.array(["a","b","c","d"])
print(strarray)
print(strarray.dtype)

floatarray = np.array([1.1,2.2,3.3,4.4,5.5])
print(floatarray)
print(floatarray.dtype)

unsignedarray = np.array([1,2,3,4,5,6,7,8] , dtype = "u2")
print(unsignedarray)
print(unsignedarray.dtype)
#Explanation : u1 denotes for 8bits
#Explanation : u2 denotes for 16bits
#Explanation : u4 denotes for 32bits
#Explanation : u8 denotes for 64bits

complexarray = np.array([1+2j,2+2j],dtype = "c8") #c8 is complex64
print(complexarray)
print(complexarray.dtype)

timedeltaarray = np.array([1,2,3,5,6] , dtype = "m8[D]")
print(timedeltaarray)
print(timedeltaarray.dtype)
#variations = m8[h], m8[s] for hours and seconds

datetimearray = np.array(['2025-08-10' , '2024-09-12'] , dtype = "M8[D]")
print(datetimearray)
print(datetimearray.dtype)
#variations = M8[ms] , M8[s] for miliseconds and seconds

objectarray = np.array([1,2,3,'Hi',"Aerospace",5] , dtype = "O")
print(objectarray)
print(objectarray.dtype)

stringarray = np.array(["Hello","hi","bye"],dtype = 'S5')
print(stringarray)
print(stringarray.dtype)

[ True False  True False]
bool
[1 2 3 4 5]
int64
['a' 'b' 'c' 'd']
<U1
[1.1 2.2 3.3 4.4 5.5]
float64
[1 2 3 4 5 6 7 8]
uint16
[1.+2.j 2.+2.j]
complex64
[1 2 3 5 6]
timedelta64[D]
['2025-08-10' '2024-09-12']
datetime64[D]
[1 2 3 'Hi' 'Aerospace' 5]
object


## Math Operations

In [ ]:
# MATH OPS with numpy arrays

import numpy as np

matharray = np.array([1,2,3,4,45,3])
math2darray = np.array([ [1,2,3,4,5] , [6,7,8,9,10] ])

# MATH Functions

print(f"Sum of the 1D array is :" , np.sum(matharray))
print(f"Mean of the 1D array : {np.mean(matharray)}")
print(f"Min of the 1D array : {np.min(matharray)}")
print(f"Max of the 1D array : {np.max(matharray)}")
print(f"Product of the 1D array : {np.prod(matharray)}")
print(f"Standard Deviation of the 1D array : {np.std(matharray)}")


print(f"Column wise sum in 2D array : {np.sum(math2darray, axis = 0)}") #column wise sum
print(f"Row wise sum in 2D array: {np.sum(math2darray, axis = 1)}") #row wise sum

print(f"Column wise product in 2D array: {np.prod(math2darray, axis = 0)}") #column wise prod
print(f"Row wise product in 2D array : {np.prod(math2darray, axis = 1)}") #row wise prod


# cumsum() #for cumulative sum
# cumprod() #for cumulative prod

print(f"cumulative Sum  1D array: {np.cumsum(matharray)}")
print(f"cumulative Product 1D array: {np.cumprod(matharray)}")
print(f"Normal Sum 1D array : {np.sum(matharray)}")

# Absolute and Rounding of array elements in Numpy

examplearray = np.array([-1.7,2.4,3.6,-4.8])

print(f"Absolute of this array : {np.abs(examplearray)}")
print(f"Round of this array : {np.round(examplearray)}")
print(f"Floor of this array : {np.floor(examplearray)}")
print(f"Ceiling of this array : {np.ceil(examplearray)}")

Sum of the 1D array is : 58
Mean of the 1D array : 9.666666666666666
Min of the 1D array : 1
Max of the 1D array : 45
Product of the 1D array : 3240
Standard Deviation of the 1D array : 15.828946760778354
Column wise sum in 2D array : [ 7  9 11 13 15]
Row wise sum in 2D array: [15 40]
Column wise product in 2D array: [ 6 14 24 36 50]
Row wise product in 2D array : [  120 30240]
cumulative Sum  1D array: [ 1  3  6 10 55 58]
cumulative Product 1D array: [   1    2    6   24 1080 3240]
Normal Sum 1D array : 58
Absolute of this array : [1.7 2.4 3.6 4.8]
Round of this array : [-2.  2.  4. -5.]
Floor of this array : [-2.  2.  3. -5.]
Ceiling of this array : [-1.  3.  4. -4.]


## Array Indexing in Numpy

In [ ]:
narray = np.array([1,2,3,4,5,6])
# Numpy Arrays do maintain positive and negative indexes

# Indexing in 1D array
print(narray[-2])
print(narray[1])

# Indexing in 2D array
n2darray = np.array([[1,2,3],[4,5,6]])
print(n2darray)

print(n2darray[0][0]) #first [] denotes indexed row and second [] denotes indexed column
print(n2darray[0][1])
print(n2darray[0][2])
print(n2darray[1][0])
print(n2darray[1][1])
print(n2darray[1][2])

# Indexing in a 3D Array
n3darray = np.array([ [ [1,2,3] , [4,5,6] ] , [ [7,8,9] , [10,11,12] ] ])
# n3darray = np.array([[[],[]],[[],[]]])
print(n3darray)

print(n3darray[0][0][0])
print(n3darray[0][0][1])
print(n3darray[0][0][2])
print(n3darray[0][1][0])
print(n3darray[0][1][1])
print(n3darray[0][1][2])

print(n3darray[1][0][0])
print(n3darray[1][0][1])
print(n3darray[1][0][2])
print(n3darray[1][1][0])
print(n3darray[1][1][1])
print(n3darray[1][1][2])

5
2
[[1 2 3]
 [4 5 6]]
1
2
3
4
5
6
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
1
2
3
4
5
6
7
8
9
10
11
12


**Array Indexing with negative indexes**

In [ ]:
# Numpy arrays also follow negative indexes like normal arrays or Strings
import numpy as np

n3darray = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

# Fetch the element 8 with negative indexes

print(n3darray[-1][-2][-2])

print(n3darray[1][0][1])



8
8


## Numpy Array Slicing

In [ ]:
#Numpy array slicing is performed very similarly as normal arrays and strings

slicearray = np.array([20,25,30,35,40,45,50,55,60])

print(slicearray[2:4]) #slicing with 2 parameters
print(slicearray[3:8])

print(slicearray[:6]) # start to 5th index
print(slicearray[2:]) # 2nd to end

print(slicearray[::2]) # slicing with 3 parameters and third is used to skip (values with 10 divisible)

print(slicearray[1::2]) # Here starting with first index and going till end with skip of 1

print(slicearray[1::-1]) # 1st se start hua end tag jayega and -1 ka skip means reverse mai jayega toh reverse mai do elements hai 20 hence array is [25,20]

print(slicearray[-3:-1]) # Negative slicing


# Slicing in 2D array

slice2darray = np.array([[1,2,3,4,5] , [6,7,8,9,10]]) # The first bracket [] grabs the array inside 2d array and second bracket [] is used to iterate over the selected array

print(slice2darray[0][0:]) # This will print first array in 2d array and print all the elements

print(slice2darray[0:][0:]) # Prints the whole 2d array

print(slice2darray[0:2 , 1 : 4])






[30 35]
[35 40 45 50 55]
[20 25 30 35 40 45]
[30 35 40 45 50 55 60]
[20 30 40 50 60]
[25 35 45 55]
[25 20]
[50 55]
[1 2 3 4 5]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[2 3 4]
 [7 8 9]]


## Numpy array shape

In [ ]:
# Shape in a numpy array is the exact number of elements in each direction
# We determine the shape of a numpy array through array.shape attribute

import numpy as np

n_zero_array = np.array(1)
print(n_zero_array)
print(n_zero_array.shape)
print(n_zero_array.ndim)

n_one_array = np.array([1,2,3,4,5])
print(n_one_array)
print(n_one_array.shape)
print(n_one_array.ndim)

n_two_array = np.array([[1,2,3,10] , [4,5,6,9]])
print(n_two_array)
print(n_two_array.shape) # (2,4) Here the first element is refering the rows and columns
print(n_two_array.ndim)

n_three_array = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(n_three_array)
print(n_three_array.shape) # So (2,2,3) means: 👉 You have 2 blocks,👉 Each block has 2 rows, 👉 Each row has 3 columns.
print(n_three_array.ndim)


1
()
0
[1 2 3 4 5]
(5,)
1
[[ 1  2  3 10]
 [ 4  5  6  9]]
(2, 4)
2
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
3


## Reshaping a Numpy array

To reshape a numpy array, we make use of the reshape() function

Reshaping can help us in chaging the dimensions of an array

We can increase the dimensions/ decrease the dimensions(Flattening)


In [ ]:
# Reshaping an one dimensional array into a 2D array

import numpy as np

nbaseaaray = np.array([1,2,3,4,5,6])

print(nbaseaaray)
print(nbaseaaray.shape)

# nreshapedarray = nbaseaaray.reshape(2,3) # Here we are converting the 1D array into 2D array

# print(nreshapedarray)
# print(nreshapedarray.shape)

# nreshapedarray = nbaseaaray.reshape(2,3,1) # Here we are converting the 1D array into 3D array
#nreshapedarraym = nbase3darray.reshape(2,3,2)
#print(nreshapedarraym)


# print(nreshapedarray)
# print(nreshapedarray.shape)

# Flattening

nbase3darray = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(nbase3darray)
nres3array = nbase3darray.reshape(-1) # -1 used to flatten the selected array
print(nres3array)



[1 2 3 4 5 6]
(6,)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


## Iterating Through Numpy Array

In [ ]:
import numpy as np

noneitarray = np.array([2,3,4,5])
for i in noneitarray:
  print(i)

ntwoitarray = np.array([ [1,2,3] , [2,3,4] ])
for i in ntwoitarray:
  print(i)

nthreearray = np.array([ [ [1,2,3] , [4,5,6] ] , [ [7,8,9] , [10,11,12] ] ])
for i in nthreearray:
  print(i)

2
3
4
5
[1 2 3]
[2 3 4]
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


## Joining / Adding 2 numpy arrays

In [ ]:
# To join 2 numpy arrays we make use of the concatenate() method

import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr3 = np.concatenate((arr1,arr2))
print(arr3)

# Addition of arrays through stack
# stack()
# vstack()
# hstack()
# dstack()
# column_stack()

# Using Stack()

n1 = np.array([1,2,3,4,5])
n2 = np.array([5,6,7,8,9])
n4 = np.array([ [1,2,3] , [4,5,6] ])
n5 = np.array([["a","b","c"],["d","e","f"]])

resultant_aray = np.stack((n1,n2))
n3 = np.stack((n1,n2),axis=0) # axis 1 will make a vertical arrangement and 0 for horizontal

print("\n",n3)
print("\n",resultant_aray)

# Using vStack() - we can change the axis of stack and in normal above stack we can change the orientation

resultantvarray = np.vstack((n1,n2))
print("\n",resultantvarray)

# Using hStack() - only have the orientation to arrange in horizontal way

resultantharray = np.hstack((n1,n2))
print("\n",resultantharray)

# Using dStack() - creates 3D stack height wise
resultantdarray = np.dstack((n1,n2))
result1 = np.dstack((n4,n5))
print("\n",result1)
print("\n" , resultantdarray)
print(resultantdarray.shape)

# Using columnStack() - 2D array height wise
resultantcarray = np.column_stack((n1,n2))
result2 = np.column_stack((n4,n5))
print("\n",result2)
print("\n",resultantcarray)
print(resultantcarray.shape)


[1 2 3 4 5 6]

 [[1 2 3 4 5]
 [5 6 7 8 9]]

 [[1 2 3 4 5]
 [5 6 7 8 9]]

 [[1 2 3 4 5]
 [5 6 7 8 9]]

 [1 2 3 4 5 5 6 7 8 9]

 [[['1' 'a']
  ['2' 'b']
  ['3' 'c']]

 [['4' 'd']
  ['5' 'e']
  ['6' 'f']]]

 [[[1 5]
  [2 6]
  [3 7]
  [4 8]
  [5 9]]]
(1, 5, 2)

 [['1' '2' '3' 'a' 'b' 'c']
 ['4' '5' '6' 'd' 'e' 'f']]

 [[1 5]
 [2 6]
 [3 7]
 [4 8]
 [5 9]]
(5, 2)


## Splitting Numpy arrays

In [ ]:
# To split numpy array we make use of the numpy.split() method

# Splitting a 1D array
import numpy as np

n1 = np.array([1,2,3,4,5,6,7])

resarray = np.array_split(n1,2)
print(resarray)

[array([1, 2, 3, 4]), array([5, 6, 7])]


In [ ]:
# Accessing the splitted arrays
# make use of the indexes

import numpy as np

n1 = np.array([1,2,3,4,5,6,7])

resarray = np.array_split(n1,2) # The second params is used to divide in that number of arrays
print(resarray)

print("\n",resarray[0])
print(resarray[1])
print(type(resarray))

[array([1, 2, 3, 4]), array([5, 6, 7])]

 [1 2 3 4]
[5 6 7]
<class 'list'>


In [ ]:
# Splitting a 2D array

import numpy as np

n2 = np.array([ [1,2,3,4] , [5,6,7,8] ])

res_array = np.array_split(n2,2)
print(res_array)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


## Sorting A Numpy array

In [ ]:
# To sort a numpy array we make use of the .sort() function

import numpy as np

# 1D ARRAY SORTING

n1 = np.array([21,34,22,1,45,31])
n2 = np.array(["aww" , "sab" , "wswsc" , "d" , "e" , "f"])

print("Unsorted array : ",n1)
print("Sorted Array : ",np.sort(n1))

print("\nUnsorted array : ",n2)
print("Sorted Array : ",np.sort(n2))


# 2D SORTING - It sorts 1D array wise not whole 2D array

n3 = np.array([ [1,34,43,12] , [44,33,4,55] ])

print("\nUnsorted 2D Array : \n",n3)
print("Sorted 2D Array : \n",np.sort(n3))

Unsorted array :  [21 34 22  1 45 31]
Sorted Array :  [ 1 21 22 31 34 45]

Unsorted array :  ['aww' 'sab' 'wswsc' 'd' 'e' 'f']
Sorted Array :  ['aww' 'd' 'e' 'f' 'sab' 'wswsc']

Unsorted 2D Array : 
 [[ 1 34 43 12]
 [44 33  4 55]]
Sorted 2D Array : 
 [[ 1 12 34 43]
 [ 4 33 44 55]]


In [ ]:
# Finding an element's index from an array
# We make use of where() function to do it

import numpy as np

n1 = np.array([1,2,34,65,33,5,6,7,33,33])

nresval = np.where(n1 == 33)
print(nresval)

(array([4, 8, 9]),)


# Pandas

Pandas is a powerful open-source data analysis and manipulation library for Python. It is built on top of the NumPy library and provides data structures like DataFrames and Series, which are essential for working with structured data.

**Key Features:**

*   **DataFrame:** A 2-dimensional labeled data structure with columns of potentially different types. It's similar to a spreadsheet or SQL table.
*   **Series:** A 1-dimensional labeled array capable of holding any data type.
*   **Data Manipulation:** Provides tools for cleaning, transforming, merging, and reshaping data.
*   **Data Analysis:** Offers functionalities for aggregation, filtering, and selecting data.
*   **File I/O:** Supports reading and writing data from various file formats like CSV, Excel, SQL databases, etc.

**Why use Pandas?**

*   **Ease of Use:** Provides intuitive and easy-to-use data structures and functions.
*   **Performance:** Optimized for performance, especially for large datasets.
*   **Flexibility:** Can handle various types of data and operations.
*   **Integration:** Works well with other Python libraries for data visualization and machine learning.

In [ ]:
!pip install pandas

In [ ]:
# Pandas
# An open source library which is considered to be one of the most powerful libraries
# for data analysis + data manipulation in Python

# Pandas is used mainly for data cleaning, reading the data, from small/ large datasets, external CSVs, Excel, JSON etc
# and making it relevant for data science

## Pandas Dataframe

**Pandas DataFrames are created by pandas.DataFrame() method**

**Pandas DataFrames are a form of tabular structured display of data.**

**Parameters inlcuded in this DataFrame() method are :**

*data = the exact data that you are trying to convert into a dataframe*

*index = gives us the index of a specified cell(s)*

*dtype = gives us the datatype of each column*

*column = to manipulate column labels*

*copy = to copy the data into another DataFrame*

In [ ]:
import pandas as pd

# Below is Mock Data

data = {
    'Student' : ['Raj', 'Abhishek', 'Debashish', 'Sanket', 'Kalash'],
    'Subject' : ['Python', 'Sanskrit', 'JavaScript', 'Java', 'Biology'],
    'Marks' : [72,88,2,33,99]
}

# Now Converting a given dictionary into a dataframe

df = pd.DataFrame(data)
print(df)

# Providing indexes to each row

df1 = pd.DataFrame(data , index=['rank1','rank2','rank3','rank4','rank5'])
print("\n\n",df1)

# Accessing these elements (a group of row and column(cell))
# To access elements we make use of the pandas.loc() method

print("\n\n" , df1.loc["rank1" , "Student"]) # syntax : loc['row_name','column_name']

# We use iloc() method for accessing elements through indexes

print("\n\n", df1.iloc[2,0]) # syntax : iloc['row_index','column_index']
print("\n\n", df1.iloc[[2,3],[]])

# Accessing the columns :
print("\n\n")
print("Columns: \n")
for col in df1:
  print(col)

     Student     Subject  Marks
0        Raj      Python     72
1   Abhishek    Sanskrit     88
2  Debashish  JavaScript      2
3     Sanket        Java     33
4     Kalash     Biology     99


          Student     Subject  Marks
rank1        Raj      Python     72
rank2   Abhishek    Sanskrit     88
rank3  Debashish  JavaScript      2
rank4     Sanket        Java     33
rank5     Kalash     Biology     99


 Raj


 Debashish


 Empty DataFrame
Columns: []
Index: [rank3, rank4]



Columns: 

Student
Subject
Marks


## Pandas DataFrames - Attributes and Methods

In [ ]:
# dtypes
# ndim
# index
# size
# shape
# T - Transpose changes rows to columns, columns to rows(2,3) - (3,2)
# head() - first 5 rows
# tail() - last 5 rows

In [ ]:
data = {
    'Student' : ['Raj', 'Abhishek', 'Debashish', 'Sanket', 'Kalash','Jacob','King','Jack'],
    'Subject' : ['Python', 'Sanskrit', 'JavaScript', 'Java', 'Biology','Sorcery','Hotel management','casino player'],
    'Marks' : [72,88,2,33,99,44,56,78]
}

dataframe2 = pd.DataFrame(data, index = ['Index1','Index2','Index3','Index4','Index5','Index6','Index7','Index8'])

print(dataframe2)

#Datatypes in the Dataframe

print("\n\nDatatypes in this dataframe\n",dataframe2.dtypes)

#Dimensions in this Dataframe

print("\n\nDimensions in this dataframe : ",dataframe2.ndim)

#Shape in this Dataframe

print("\n\nShape of this dataframe : ",dataframe2.shape)

#Index in this Dataframe

print("\n\nIndexes in this dataframe : ",dataframe2.index)

#Size in this Dataframe

print("\n\nSize of this dataframe : ",dataframe2.size)

#Transpose of this Dataframe

print("\n\nTranspose of this dataframe : \n",dataframe2.T)

#Methods in DataFrames

# Using head() - prints the first 5 rows
print("\n\nFirst 5 rows of this dataframe : \n",dataframe2.head())
# Specifying this parameter
print("\n\nFirst 2 rows of this dataframe : \n",dataframe2.head(2))

# Using tail() - prints the last 5 rows
print("\n\nLast 5 rows of this dataframe : \n",dataframe2.tail())
# Specifying this parameter
print("\n\nLast 2 rows of this dataframe : \n",dataframe2.tail(2))


          Student           Subject  Marks
Index1        Raj            Python     72
Index2   Abhishek          Sanskrit     88
Index3  Debashish        JavaScript      2
Index4     Sanket              Java     33
Index5     Kalash           Biology     99
Index6      Jacob           Sorcery     44
Index7       King  Hotel management     56
Index8       Jack     casino player     78


Datatypes in this dataframe
 Student    object
Subject    object
Marks       int64
dtype: object


Dimensions in this dataframe :  2


Shape of this dataframe :  (8, 3)


Indexes in this dataframe :  Index(['Index1', 'Index2', 'Index3', 'Index4', 'Index5', 'Index6', 'Index7',
       'Index8'],
      dtype='object')


Size of this dataframe :  24


Transpose of this dataframe : 
          Index1    Index2      Index3  Index4   Index5   Index6  \
Student     Raj  Abhishek   Debashish  Sanket   Kalash    Jacob   
Subject  Python  Sanskrit  JavaScript    Java  Biology  Sorcery   
Marks        72        88   

In [ ]:
import pandas as pd

data1 = {
    'Student' : ['Raj', 'Abhishek', 'Debashish', 'Sanket'],
    'Subject' : ['Python', 'Sanskrit', 'JavaScript', 'Java'],
    'Marks' : [72,88,2,33]
}

data2 ={
    'Name' : ['Kalash','Jacob','King','Jack'],
    'Fields' : ['Biology','Sorcery','Hotel management','casino player'],
    'Ranks' : [99,44,56,78]
}

dataframe1 = pd.DataFrame(data1)
dataframe2 = pd.DataFrame(data2)

print(dataframe1)
print("\n\n", dataframe2)
# We make use of the join() method to join 2 different dataframes with each other.
print("\n\nAfter joining:\n",dataframe1.join(dataframe2))


resultant = pd.concat([dataframe1,dataframe2])
print("\n\nAfter Concat:\n",resultant)

     Student     Subject  Marks
0        Raj      Python     72
1   Abhishek    Sanskrit     88
2  Debashish  JavaScript      2
3     Sanket        Java     33


      Name            Fields  Ranks
0  Kalash           Biology     99
1   Jacob           Sorcery     44
2    King  Hotel management     56
3    Jack     casino player     78


After joining:
      Student     Subject  Marks    Name            Fields  Ranks
0        Raj      Python     72  Kalash           Biology     99
1   Abhishek    Sanskrit     88   Jacob           Sorcery     44
2  Debashish  JavaScript      2    King  Hotel management     56
3     Sanket        Java     33    Jack     casino player     78


After Concat:
      Student     Subject  Marks    Name            Fields  Ranks
0        Raj      Python   72.0     NaN               NaN    NaN
1   Abhishek    Sanskrit   88.0     NaN               NaN    NaN
2  Debashish  JavaScript    2.0     NaN               NaN    NaN
3     Sanket        Java   33.0     NaN   

## Pandas Series

In [ ]:
# Pandas Series --> is a kind of one dimensional array which stores the data in a comlumn like structure with indexes.
# We make use of Series() method to create pandas series
#Parameters / Arguments of the series() method


#data
#index
#column
#copy
#index_col

In [ ]:
import pandas as pd

# Declaring the series

data = [10,20,30,40,50]

#Creating a Pandas Series
series = pd.Series(data)

print(series)

#Accessing elements from the series
print("\n",series[3])

series1 = pd.Series(data , index = ["Index1" , "Index2" , "Index3" , "Index4" , "Index5"])
print("\n\n",series1)

#Accessing elements through custom indexes
print("\n",series1["Index3"])


0    10
1    20
2    30
3    40
4    50
dtype: int64

 40


 Index1    10
Index2    20
Index3    30
Index4    40
Index5    50
dtype: int64

 30


## Pandas attributes and methods

In [ ]:
# 👉 Attributes = Give you information about your data (no parentheses () required).
# 👉 Methods = Perform an action or operation on your data (need parentheses ()).

# 🔹 Attributes
# 	•	dtype → Returns data type of values.
# 	•	ndim → Number of dimensions (Series=1, DataFrame=2).
# 	•	size → Total number of elements.
# 	•	shape → Tuple of (rows, columns).
# 	•	index → Row labels/index.
# 	•	hasnans → Checks if any NaN (missing) values exist.

# 🔹 Methods
# 	•	head() → Shows first 5 rows (or given n).
# 	•	tail() → Shows last 5 rows (or given n).
# 	•	info() → Displays dataset summary (index, columns, dtypes, nulls, memory).

In [ ]:
import pandas as pd

data1 = [10,20,30,40,50,60,"hello","hi",None]

series1 = pd.Series(data1)
print(series1)

# Using dtype attribute
print("\n\nDatatype of this Series:",series1.dtype)

# Using ndim attribute
print("\n\nDimensions of this Series:",series1.ndim)

# Using size attribute
print("\n\nSize of this Series:",series1.size)

# Using size attribute
print("\n\nSize of this Series:",series1.size)

# Using hasnans attribute
print("\n\nSeries has None value ? :",series1.hasnans)

# Using index attribute
print("\n\nIndex of series",series1.index)


# Method in Pandas.Series

# Using head() method
print("\n\nFirst 5 rows of this series : \n",series1.head())
print("\n\nFirst 2 rows of this series : \n",series1.head(2))

# Using tail() method
print("\n\nLast 5 rows of this series : \n",series1.tail())
print("\n\nLast 3 rows of this series : \n",series1.tail(3))

# Using info() method
print("\n\n",series1.info())

0       10
1       20
2       30
3       40
4       50
5       60
6    hello
7       hi
8     None
dtype: object


Datatype of this Series: object


Dimensions of this Series: 1


Size of this Series: 9


Size of this Series: 9


Series has None value ? : True


Index of series RangeIndex(start=0, stop=9, step=1)


First 5 rows of this series : 
 0    10
1    20
2    30
3    40
4    50
dtype: object


First 2 rows of this series : 
 0    10
1    20
dtype: object


Last 5 rows of this series : 
 4       50
5       60
6    hello
7       hi
8     None
dtype: object


Last 3 rows of this series : 
 6    hello
7       hi
8     None
dtype: object
<class 'pandas.core.series.Series'>
RangeIndex: 9 entries, 0 to 8
Series name: None
Non-Null Count  Dtype 
--------------  ----- 
8 non-null      object
dtypes: object(1)
memory usage: 204.0+ bytes


 None


## Reading CSV Files

In [ ]:
# TO read CSV files in pandas , we use pd.read_csv() method
from google.colab import files
import pandas as pd

uploaded = files.upload()

csvdf = pd.read_csv('USERDETAILS.csv' , index_col="Name")

print("\n\nFirst n rows :\n" , df.head())

Saving USERDETAILS.csv to USERDETAILS (2).csv


First n rows :
       Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   25    Los Angeles


## Reading an Excel File

In [ ]:
# To read an excel file, we make use of the pd.read_excel() method
from google.colab import files
import pandas as pd

uploaded = files.upload()

df1 = pd.read_excel("readingexcelfile.xlsx")
print("\n\nFirst 5 rows\n",df1.head())
print("\n\nLast 2 rows\n",df1.tail(2))

Saving readingexcelfile.xlsx to readingexcelfile.xlsx


First 5 rows
       Name  Age           City
0    Alice   25          India
1      Bob   30        Denmark
2  Charlie   35         Boston
3    David   40  San Francisco
4      Eve   45      Dhinchakk


Last 2 rows
     Name  Age           City
3  David   40  San Francisco
4    Eve   45      Dhinchakk


## Column Selection in pandas


In [ ]:
# Fetching columns through labels(column_names)
res = csvdf['Age']
print(res)

# Fetching multiple columns :
resmultiple = csvdf[['Age','City']]
print("\n\n",resmultiple)

# Fetching rows through customised indexes in loc
resloc = csvdf.loc["Charlie"]
print("\n\n", resloc)

# Fetching rows through iloc()

resiloc = csvdf.iloc[2]
print(resiloc)

Name
Alice      25
Bob        30
Charlie    25
Name: Age, dtype: int64


          Age           City
Name                       
Alice     25       New York
Bob       30  San Francisco
Charlie   25    Los Angeles


 Age              25
City    Los Angeles
Name: Charlie, dtype: object
Age              25
City    Los Angeles
Name: Charlie, dtype: object
