<a href="https://colab.research.google.com/github/Aerospace-prog/Python-For-AI-Ml/blob/main/Python_For_Ai_Ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Strings**

There are three primary ways to declare strings in Python:

1.  **Single Quotes (`'`)**: Useful for simple, single-line strings.
2.  **Double Quotes (`"`)**: Also used for simple, single-line strings. Often preferred when the string contains single quotes.
3.  **Triple Quotes (`"""` or `'''`)**: Used for multi-line strings, which can span across multiple lines in your code. These are also commonly used for docstrings.

In [ ]:
# Kinds of string declarations

str1 = 'hello'
str2 = "hello"
str3 = """hello
          kaise ho aap
        """

 # Note : Strings are immutable in nature


print(len(str2)) # ==> 5



5


**Indexing in strings**

Indexing in strings allows you to access individual characters within a string using their position (index).

*   **Positive Indexing**: Starts from 0 for the first character and increases by 1 for each subsequent character.
*   **Negative Indexing**: Starts from -1 for the last character and decreases by 1 for each preceding character.

You can access a character using square brackets `[]` with the index inside.

In [ ]:
# Let's assume we have a string for demonstration
str2 = "HelloWorld"

# str2[0:4] → Extracts characters from index 0 to 3 (end index 4 is excluded).
# This means it will take the substring "Hell".
print(str2[0:4])   # Output: Hell

# str2[:] → Returns the entire string because no start or end index is given.
# This is the same as making a copy of the string.
print(str2[:])     # Output: HelloWorld

# str2[:4] → Omits the start index (defaults to 0) and goes till index 3.
# Equivalent to str2[0:4].
print(str2[:4])    # Output: Hell

# str2[0:] → Omits the end index (defaults to the end of the string).
# Extracts from index 0 to the end.
print(str2[0:])    # Output: HelloWorld

Hell
HelloWorld
Hell
HelloWorld


**Slicing with 3 parameters - [startindex : endindex : step]**

In [ ]:
numStr = "0123456789"

# Start at index 2 and take every 2nd character → indices 2,4,6,8
print(numStr[2::2])   # Output: 2468

# Start at index 1 and take every 2nd character → indices 1,3,5,7,9
print(numStr[1::2])   # Output: 13579

characterAtIndex1 = numStr[1]
print(characterAtIndex1)

#Type Checking for string
print(type(characterAtIndex1))



exampleString = "Aerospace"

# Negative slicing counts from the end:
# Index positions:  A   e   r   o   s   p   a   c   e
# Positive index:   0   1   2   3   4   5   6   7   8
# Negative index:  -9  -8  -7  -6  -5  -4  -3  -2  -1

# exampleString[-6:-1] → take characters from -6 (index of 'o') up to -1 (excluded, index of 'e')
print(exampleString[-6:-1])   # Output: ospac

2468
13579
1
<class 'str'>
ospac


**String Functions**

In [ ]:
randomStr = "polarisSchoolofTech"

# Get the total number of characters in the string
print(len(randomStr))   # Output: 18

# Capitalize the first character, rest in lowercase
print(randomStr.capitalize())   # Output: Polarisschooloftech

# Convert entire string to uppercase
print(randomStr.upper())   # Output: POLARISSCHOOLOFTECH

# Convert entire string to lowercase
print(randomStr.lower())   # Output: polarisschooloftech

# Check if string starts with "polaris"
print(randomStr.startswith("polaris"))   # Output: True

# Check if string ends with "techonologia"
print(randomStr.endswith("techonologia"))   # Output: False

# Convert string into Title Case (first letter of each word capitalized)
print(randomStr.title())   # Output: Polarisschooloftech

# Make only the first 7 characters uppercase
print(randomStr[:7].upper())   # Output: POLARIS

# Find index of first occurrence of substring "School" (-1 if not found)
print(randomStr.find("School"))   # Output: 7

# Replace "SchoolofTech" with "SchoolOfHack"
print(randomStr.replace("SchoolofTech", "SchoolOfHack"))   # Output: polarisSchoolOfHack

# Count occurrences of 'o'
print(randomStr.count("o"))   # Output: 3


# PROBLEM : 1 - FIND ALL WHITESPACES INDEX IN WHOLE STRING :)

text = "Python is a fun programming language"

# find first whitespace
pos = text.find(' ')

while pos != -1:   # keep looping until no space is found
    print("Whitespace found at index:", pos)

    # find next whitespace starting after current position
    pos = text.find(' ', pos + 1)

19
Polarisschooloftech
POLARISSCHOOLOFTECH
polarisschooloftech
True
False
Polarisschooloftech
POLARIS
7
polarisSchoolOfHack
4
Whitespace found at index: 6
Whitespace found at index: 9
Whitespace found at index: 11
Whitespace found at index: 15
Whitespace found at index: 27


# **Functions in python**

Functions in Python are blocks of reusable code that perform a specific task. They help organize code, make it more readable, and reduce redundancy.

**Key Concepts:**

*   **Defining a Function:** Functions are defined using the `def` keyword, followed by the function name, parentheses `()`, and a colon `:`. The code block for the function is indented.
*   **Function Name:** Should be descriptive and follow Python naming conventions (lowercase with underscores).
*   **Parameters:** These are values passed into the function when it is called. They are specified within the parentheses in the function definition.
*   **Arguments:** These are the actual values passed to the function when it is called.
*   **Return Statement:** The `return` keyword is used to send a value back from the function to the part of the code that called it. If no `return` statement is used, the function returns `None` by default.
*   **Calling a Function:** To execute the code within a function, you "call" it by using the function name followed by parentheses `()`, including any necessary arguments.

**Benefits of using Functions:**

*   **Reusability:** Write code once and use it multiple times.
*   **Modularity:** Break down complex problems into smaller, manageable parts.
*   **Readability:** Makes code easier to understand and maintain.
*   **Abstraction:** Hide the complex details of a task behind a simple function call.

In [ ]:
num1 = int(input("Enter Number 1 "))

num2 = int(input("Enter Number 2 "))

sum  = num1 + num2

print(f"The sum of these numbers is : {sum}")

Enter Number 1 12
Enter Number 2 23
The sum of these numbers is : 35


In [ ]:
def calulateNums() : #Function declaration
  num1 = int(input("Enter Number 1 "))
  num2 = int(input("Enter Number 2 "))
  sum  = num1 + num2                              #Function definition
  print(f"The sum of these numbers is : {sum}")


calulateNums() #Function call

Enter Number 1 12
Enter Number 2 12
The sum of these numbers is : 24
Enter number to get cube1
The cube of 1 is 1


In [ ]:
def cube() :
  num1 = int(input("Enter number to get cube "))
  cube = num1 * num1 * num1
  print(f"The cube of {num1} is {cube}")

cube()

Enter number to get cube 2
The cube of 2 is 8


**Function With Arguments**

There are to types of functions in python = 1. Built in. 2. User defined

In [ ]:
def greet(name) :
  print(f"Good Afternoon{name}")

greet("Aerospace")


def greet1(name , title = "CHIP"):
  print(f"Hello Coder {name} {title}")

greet1("Aerosapce", 'Prog')

Good AfternoonAerospace
Hello Coder Aerosapce Prog


In [ ]:
def func1(val):
  return val

func1(12)

12

Recursion Example for function


In [ ]:
def fact (n) :
  if(n == 1 or n == 0):
    return 1

  return n * fact(n-1)

print(fact(5))

120


# **Collections**

Collections in Python are containers that are used to store collections of data. They are a fundamental part of Python and are used extensively in programming. Python offers several built-in collection types, each with its own characteristics and use cases.

**Key Built-in Collection Types:**

1.  **Lists (`list`)**:
    *   Ordered, mutable (changeable) sequence of elements.
    *   Elements are enclosed in square brackets `[]`.
    *   Can contain elements of different data types.
    *   Supports indexing and slicing.
    *   Examples: `[1, 2, 3]`, `['apple', 'banana', 'cherry']`

2.  **Tuples (`tuple`)**:
    *   Ordered, immutable (unchangeable) sequence of elements.
    *   Elements are enclosed in parentheses `()`.
    *   Can contain elements of different data types.
    *   Supports indexing and slicing.
    *   Often used for heterogeneous data (different types) and when the sequence of elements is fixed.
    *   Examples: `(1, 2, 3)`, `('apple', 'banana')`

3.  **Sets (`set`)**:
    *   Unordered collection of unique elements.
    *   Elements are enclosed in curly braces `{}` (except for an empty set, which is created using `set()`).
    *   Does not support indexing or slicing.
    *   Useful for membership testing, removing duplicates, and performing mathematical set operations (union, intersection, difference).
    *   Examples: `{1, 2, 3}`, `{'apple', 'banana'}`

4.  **Dictionaries (`dict`)**:
    *   Unordered collection of key-value pairs.
    *   Key-value pairs are enclosed in curly braces `{}`.
    *   Keys must be unique and immutable (like strings, numbers, or tuples).
    *   Values can be of any data type.
    *   Used to store data in a key-value format for efficient lookup.
    *   Examples: `{'name': 'John', 'age': 30}`, `{'a': 1, 'b': 2}`

Understanding these collection types and their differences is crucial for writing efficient and effective Python code.

**List**

In [ ]:
#List - Mutable and indexing maintained

list = [1,2,"hello",3,4,5,True , False , None , "hi" , 1.2]

#Get Element by indexing
print(list[1])
#Print Whole list
print(list)
#List Iterator
for i in list:
  print(i)

# Slicing in list
print(list[0:4])
print(list[::2])
print(list[::4])

#Functions in list
list1 = [1,232,453,6,4,32,97]

list1.sort()
print(list1)

list1.reverse()
print(list1)

list1.append(20)
print(list1)

list1.insert(3,47)
print(list1)

list1.index(32)

list1.pop(3)
print(list1)

list1.remove(453)
print(list1)

"""
Features of List :
ordered collection of elements
heterogenours data
mutable
indexing/slicing
allow duplicates
nested list allowed
itetrable
non - hashable

"""

2
[1, 2, 'hello', 3, 4, 5, True, False, None, 'hi', 1.2]
1
2
hello
3
4
5
True
False
None
hi
1.2
[1, 2, 'hello', 3]
[1, 'hello', 4, True, None, 1.2]
[1, 4, None]
[1, 4, 6, 32, 97, 232, 453]
[453, 232, 97, 32, 6, 4, 1]
[453, 232, 97, 32, 6, 4, 1, 20]
[453, 232, 97, 47, 32, 6, 4, 1, 20]
[453, 232, 97, 32, 6, 4, 1, 20]
[232, 97, 32, 6, 4, 1, 20]


In [ ]:
listexample = [1,2,3,4,5,6,70]
def add(listexample):
  sum = 0
  for i in listexample:
    sum = sum + i
  return sum

print(add(listexample))

91


**Tuples**

In [ ]:
#Tuple declaration

t1 = (1,2,3,3,3,"hello",True)
t2 = ()
t3 = (1,)

t1.count(3)

print(t1)

#Iterator in tuple
for i in t1:
  print(i)

print(t1[1])

#Slicing
print(t1[0:4])
print(t1[::2])
print(t1[::3])

(1, 2, 3, 3, 3, 'hello', True)
1
2
3
3
3
hello
True
2
(1, 2, 3, 3)
(1, 3, 3, True)
(1, 3, True)


**Functions In Tuple**

In [ ]:
t1.count(3)

t1.index("hello")

'''
  Features of Tuple :
  ordered collection of elements
  heterogenours data
  immutable
  indexing/slicing
  allow duplicates
  nested tuple allowed
  itetrable
  hashable
'''

5

**Dictionary**

In [ ]:
dict1 = {
    "key" : "value",
    1 : "hello",
    2 : "yellow",
    3 : "aerospace",
    "hi" : "bye",
    "bool" : True,
    "list" : [1,2,3,4,5],
    "tuple" : (1,2)
}
#The Key should be hashable --> unique/immutable

print(dict1)

{'key': 'value', 1: 'hello', 2: 'yellow', 3: 'aerospace', 'hi': 'bye', 'bool': True, 'list': [1, 2, 3, 4, 5], 'tuple': (1, 2)}


**Set - A set is an unordered collection of unique elements.**

In [ ]:
# Declaration:
s = set()
s.add(5)
s.add(24)
s.add("hello")
s.add(True)
s.add(1) # Duplicate of True → ignored
s.add(0) # Duplicate of False → ignored
print(s)
s1 = {123, 344, "hello", True, 1, 0, False}
print(s1)

{0, True, 5, 'hello', 24}
{0, True, 'hello', 344, 123}


In [ ]:
# Set Functions:
print(len(s1)) # Length of set
s1.remove(123) # Remove specific element
s1.pop() # Removes random element
s.clear() # Empty set
s1.update([67, 3, 4], {8, 11}) # Add multiple elements
print(s1)
print(s1.union({123, 345, 33})) # Union
print(s1 | {123, 345, 33}) # Equivalent union operator
print(s1.intersection({67, 3, 48})) # Intersection
print(s1 & {67, 3, 48}) # Equivalent intersection operator

# Features of a Set
# ● Unordered → no indexing.
# ● Mutable → elements can be added/removed.
# ● No duplicates → {1, True} collapses to {1}.
# ● Heterogeneous elements allowed (numbers, strings, tuples).
# ● Supports Union (|) and Intersection (&).

# File IO

**File I/O in Python**

File Input/Output (I/O) in Python allows you to interact with files on your computer. This means you can read data from files and write data to files.

Key concepts:

*   **Opening a File:** You need to open a file before you can read from it or write to it. The `open()` function is used for this. You specify the file path and the mode (e.g., 'r' for read, 'w' for write, 'a' for append).
*   **File Modes:** Different modes determine how the file is opened:
    *   `'r'` (read): Opens a file for reading. The file pointer is at the beginning.
    *   `'w'` (write): Opens a file for writing. Creates a new file if it doesn't exist or truncates the file if it exists.
    *   `'a'` (append): Opens a file for appending. Creates a new file if it doesn't exist. Data is written at the end of the file.
    *   `'x'` (exclusive creation): Creates a new file, but raises an error if the file already exists.
    *   `'t'` (text mode): The default mode. Data is treated as text.
    *   `'b'` (binary mode): Data is treated as binary.
*   **Reading from a File:** After opening in read mode, you can use methods like `read()`, `readline()`, or `readlines()` to get data from the file.
*   **Writing to a File:** After opening in write or append mode, you can use the `write()` method to put data into the file.
*   **Closing a File:** It's crucial to close a file after you're done with it using the `close()` method. This releases the file resources. Using `with open(...) as file:` is the recommended way as it automatically closes the file.

In [3]:
# There is a function which solves a purpose.

# The place of execution of any program would be your RAM

# The RAM is a volatile form of memory in which all your contents are lost , once the program terminates

# To store any form of a permanently your need files

# HDD & SSD is a form of non-volatile memory which can save files permanently



In [12]:
# Reading from Text files and writing into text files

from google.colab import files
uploaded = files.upload() # This variable is form of collection

for filename in uploaded:
  # Opens the file
  f = open(filename) #open() function - ("filename" , "operation")
  # Read the file
  data = f.read()
  #prints the data
  print(data)
  #close the file
  f.close()


Saving test.txt to test (3).txt
Hello this is text file
This is second line 
This is third line


In [33]:
#read() function variants

#readline()
#readlines()
# with - Helps you avoid explicit declaration of close()


# for filename in uploaded:
#   with open(filename, "r") as f:
#     line1 = f.readline()
#     print(line1,type(line1))
#     line2 = f.readline()
#     print(line2,type(line2))
#     line3 = f.readline()
#     print(line3,type(line3))

# for filename in uploaded:
#   with open(filename, "r") as f:
#     lines = f.readlines()
#     print(lines,type(lines))

#PRACTICE :- read from a file name animals.txt and check whether the file contains the word "hen" in it
# from google.colab import files
# uploaded = files.upload()

# for filename in uploaded:
#   with open(filename, "r") as f:
#     lines = f.readlines()
#     for line in lines:
#       if "hen" in line:
#         print(True)
#         break
#       else :
#         print(False)
#         break


# WRITE OPERATION

# f = open("test.txt", "w")
# newStr = "Hello Duniya!"
# f.write(newStr)
# f.close()

# write() is a method used with file objects in Python to write a string to a file.
# Write() with a capital 'W' is not a standard method in Python for file handling. It might be a typo or a method from a specific library or custom class.

#HERE THIS WILL NOT WORK


#APPEND OPERATION

# f = open("test.txt" , "a")
# addedStr = "\n This is new line added with append"
# f.write(addedStr)
# f.close()

"""
  Python File Modes - Definitions
===============================

Basic Modes
-----------
r   = Open for reading only (default). File must exist.
w   = Open for writing only. Creates a new file or truncates (empties) the file if it exists.
a   = Open for appending only. Creates file if it does not exist, otherwise writes at the end.

With '+' (Read + Write)
-----------------------
r+  = Open for reading and writing. File must exist. No truncation.
w+  = Open for reading and writing. Truncate file first (empties it if it exists).
a+  = Open for reading and appending. File pointer is at the end, but you can still read.

Binary / Text Modes
-------------------
rb  = Open for reading binary (e.g., images, videos). File must exist.
wb  = Open for writing binary. Truncate file first (create new if not exists).
ab  = Open for appending binary.

rt  = Open for reading text (default mode). Same as "r".
wt  = Open for writing text (truncate file). Same as "w".
at  = Open for appending text. Same as "a".

Combos
------
r+b or rb+ = Read & write binary. File must exist.
w+b or wb+ = Read & write binary, truncate first.
a+b or ab+ = Read & write binary, append if file exists.

Quick Summary Table
-------------------
| Mode | File Must Exist? | Truncate? | Pointer | Read | Write |
|------|------------------|-----------|---------|------|-------|
| r    | Yes              | No        | Start   | Yes  | No    |
| w    | No (creates)     | Yes       | Start   | No   | Yes   |
| a    | No (creates)     | No        | End     | No   | Yes   |
| r+   | Yes              | No        | Start   | Yes  | Yes   |
| w+   | No (creates)     | Yes       | Start   | Yes  | Yes   |
| a+   | No (creates)     | No        | End     | Yes  | Yes   |
| rb   | Yes              | No        | Start   | Yes  | No    |
| wb   | No (creates)     | Yes       | Start   | No   | Yes   |
| ab   | No (creates)     | No        | End     | No   | Yes   |
"""


Saving animals.txt to animals (6).txt
True


In [ ]:
# WAP to write tables from 2 to 20 in differend text files. Store them in a folder.

# for num in range(2, 21):
#     file_path = f"tables/table_{num}.txt"

#     with open(file_path, "w") as f:
#         f.write(f"Multiplication Table of {num}\n")
#         f.write("=" * 30 + "\n")
#         for i in range(1, 11):
#             f.write(f"{num} x {i} = {num * i}\n")

# print("Tables from 2 to 20 have been written inside the 'tables' folder ")


# NumPy

*NumPy*

NumPy (Numerical Python) is a fundamental library for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

**Key Features:**

*   **Powerful N-dimensional array object:** This is the core of NumPy, allowing efficient storage and manipulation of large datasets.
*   **Broadcasting:** A powerful feature that allows NumPy to work with arrays of different shapes when performing arithmetic operations.
*   **Integration:** NumPy is designed to be highly integrated with other scientific computing libraries like SciPy and Matplotlib.
*   **Performance:** NumPy operations are often much faster than equivalent Python list operations due to its underlying implementation in C.

**Why use NumPy?**

*   **Efficiency:** Working with large datasets is significantly faster.
*   **Convenience:** Provides a wide range of mathematical functions and operations that are easy to use.
*   **Foundation:** Many other scientific and data analysis libraries in Python are built on top of NumPy.

In [ ]:
                                                                  # FEATURES
# Numpy works with multi dimentional arrays
# This is an open source library which is built on python and C
# The kinds of operations on arrays numpy supports are :
## Array initialization
## Array Slicing
## Array Reshaping
## Supports zero , one and two (matrix) dimentional arrays
## Array join , Array Split

In [2]:
#Installing numpy
!pip install numpy

In [5]:
import numpy as np

#Function to create numpy arrays - numpy.array()
#Two ways to create numpy arrays - 1.Passing a list , 2. Passing a tuple

#1. Passing a tuple
npobj = np.array((1,2,3,4,5,6,7,8,9))
print(npobj)
print(type(npobj)) # N-Dimentional array

#2. Passing a list
npobj = np.array([1,2,3,4,5,6,7,8,9])
print(npobj)
print(type(npobj)) # N-Dimentional array

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


 **Dimensions of a Numpy Array**

 **To check the dimensions of a numpy array we make use of the attribute 'ndim'**

 *The kinds of Arrays that can be created are :*

 Zero Dimensional Array
 One Dimensional Array
 Two Dimensional Array (basically a matrix)

In [9]:
# 1. Zero Dimensional Array

import numpy as np

zero_dim_arr = np.array(42)

print(zero_dim_arr)
print(type(zero_dim_arr))
print(f"Dimension : {zero_dim_arr.ndim}")

42
<class 'numpy.ndarray'>
Dimension : 0


In [10]:
# 2. One Dimensional Array

import numpy as np

one_dim_arr = np.array([1, 2, 3, 4, 5])

print(one_dim_arr)
print(type(one_dim_arr))
print(f"Dimension : {one_dim_arr.ndim}")

[1 2 3 4 5]
<class 'numpy.ndarray'>
Dimension : 1


In [17]:
# 3. Two Dimensional Array

import numpy as np

two_dim_arr = np.array( [ [1,2,3,4],[5,6,7,8] ] ) # This should always be structured
print(two_dim_arr)
print(type(two_dim_arr))
print(f"Dimension : {two_dim_arr.ndim}")

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
Dimension : 2


### Initializing an Array

In [28]:
# Initializing an array

# To Initialize an empty array in numpy we use numpy.zeros() function where inside params we have (rows,columns)

import numpy as np

initArray = np.zeros( [3,4] )
print(initArray)
print(type(initArray))
print(f"Dimension : {initArray.ndim}")

# Initialize this array with some values using loops
# Make use of np.shape() - Shape is used to get elements/whole list inside matrix

arr1 = np.zeros( [2,2] )
for i in range(arr1.shape[0]):
  for j in range(arr1.shape[1]):
    arr1[i,j] = (i+1) * (j+1)

print(arr1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>
Dimension : 2
[[1. 2.]
 [2. 4.]]


### Data Types in Numpy

In [35]:
# Kinds of dtypes supported in NumPy:

# Code  | Description
# -----------------------------------
# b     | Boolean
# u     | Unsigned Integer
# m     | Timedelta64
# M     | Datetime64
# U     | Unicode String
# i     | Signed Integer
# f     | Floating Point
# c     | Complex Floating Point
# O     | Object

# To Determine the kind if data the array is holding , we use the 'dtype' attrubute

import numpy as np


int_arr = np.array( [1,2,4] )
print(int_arr)
print(int_arr.dtype) # int64


str_arr = np.array( ["hello" , "world"] )
print(str_arr)
print(str_arr.dtype) # <U5 - U(Unicode String) , 5(The maximum characters inside string model)



[1 2 4]
int64
['hello' 'world']
<U5
